language: go
go:
  - 1.11.x
  - master

env:
  global:
    - GO111MODULE=on

# this should be changed to the solutions of:
# - https://github.com/golang/go/issues/24250
# - https://github.com/go-modules-by-example/index/blob/master/017_using_gobin/README.md
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.2

jobs:
  - stage: test
    name: "Lint"
    script: golangci-lint run
  - stage: test
    name: "Unit Tests"
    script: go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - go: master

notifications:
  email: false

stages:
  - test
