git:
  depth: false

language: go
go:
  - tip
  - 1.11.x

sudo: false
dist: trusty

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - go test -v ./...

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false
