language: go
go:
  - 1.11.x
  - tip

env:
  global:
    - GO111MODULE=on

install: true

script:
  - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false
