language: go
go:
  - 1.11.x
  - tip

env:
  global:
    - GO111MODULE=on

install: true

script:
  - go test -v -race ./...

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false
